# Topics that RRT listens to
# TODO: add your own
# TODO: change this to the pose topic published particle filter
pose_topic: "gt_pose"
scan_topic: "scan"
drive_topic: "some_drive_topic"

# Topics that RRT publishes to
# TODO: add your own
# visualization

# TODO: add Parameters for RRT